# Generated by Django 2.1.5 on 2019-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('opertionTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('deptno', models.CharField(max_length=50)),
                ('deptname', models.CharField(max_length=50)),
                ('deptzhuguan', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '部门表',
                'db_table': 'demo_dept',
            },
        ),
    ]
